const express = require('express');
const router  = express.Router();
const c = require('../controllers/startup.controller');
const { protect } = require('../middleware/auth.middleware');
router.get('/',    c.getAll);
router.get('/:id', c.getOne);
router.post('/',   protect, c.create);
router.put('/:id', protect, c.update);
router.delete('/:id', protect, c.remove);
module.exports = router;
